#!/bin/sh
rm -rf lib
cp -a src lib
coffee -tcm lib
tsc -d lib/*.ts
#if [ -d lib/lib ]; then
#    mv lib/lib/* lib
#    rmdir lib/lib
#fi
#if [ -d lib/src ]; then
#    mv lib/src/* lib
#    rmdir lib/src
#fi
cp lib/domCursor.d.ts .
cp src/editor.d.ts .
